Sprint 4
habirov91/middle.messenger.praktikum.yandex pull request #4
Opened 2023-02-09 12:56 UTC by habirov91

2023-02-10 04:35 UTC, maks88sgt requested changes
Привет. Отличная работа. У тебя получился хорошо структурированный проект с довольно чистым кодом. Чтобы закрыть все критерии спринта и пойти дальше необходимо немного доработать некоторые моменты:
1. В Readme дополнить описание функциональности и использованных технологий, информацию об основных скриптах для запуска/тестирования приложения.
2. По условиям спринта тестами также должен быть покрыт модуль отправки запросов.
3. Тесты сейчас падают с ошибкой при запуске. Для корректной работы нужно донастроить парсер, чтобы во время исполнения тестов правильно резолвились path-алиасы.
4. Прекоммит хук не настроен. Нужно добавить выполнение тестов и/или проверку линтером при коммите.
5. Аудит зависимостей выдает уязвимости, которых не должно быть по условиям спринта.

2023-02-10 04:35 UTC, maks88sgt commented on .dockerignore
> +node_modules
Здесь гит ругается на отсутствие EOF символа  в конце файла. Вот здесь можно почитать почему это может быть важно https://moviecultists.com/when-to-use-eof. В идеале нужно настроить ИДЕ, чтобы это делалось автоматически

2023-02-10 04:35 UTC, maks88sgt commented on README.md
> +ссылка render.com: https://messenger-praktikum.onrender.com/
По критериям спринта Readme должно включать описание функциональности и использованных технологий, информацию о том, как собрать проект и как можно запустить тесты. Давай дополним это

2023-02-10 04:35 UTC, maks88sgt commented on package.json
> +    "mini-css-extract-plugin": "^2.6.0",
Лучше придерживаться единого подхода и использовать фиксированные версии для всех зависимостей

2023-02-12 06:07 UTC, maks88sgt requested changes
Привет. Принять работу пока не могу, т.к. не закрыты все критерии спринта. Нам осталось совсем немного:
* добавить тест сьют для роутера;
* исправить уязвимости в зависимостях. Сейчас отчет выдает 8 проблемных пакетов
<img width="338" alt="image" src="https://user-images.githubusercontent.com/49103217/218295794-497f7c7f-c333-495b-b1b6-240a2da5ce09.png">
Еще было бы неплохо разобраться с отсутствием EOF в конце файла.

2023-02-12 18:53 UTC, habirov91 commented
> Привет. Принять работу пока не могу, т.к. не закрыты все критерии спринта. Нам осталось совсем немного:
> 
> * добавить тест сьют для роутера;
> * исправить уязвимости в зависимостях. Сейчас отчет выдает 8 проблемных пакетов
> 
> <img alt="изображение" width="338" src="https://user-images.githubusercontent.com/49103217/218295794-497f7c7f-c333-495b-b1b6-240a2da5ce09.png">
> 
> Еще было бы неплохо разобраться с отсутствием EOF в конце файла.

Привет!
- Тесты для роутеры у меня есть, добавил для Request
- Уязвимости вроде исправил при npm audit пишет что все ок
- Пустую строку в dockerignore добавил

2023-02-13 03:14 UTC, maks88sgt commented
Отлично, работу принял, успехов на курсе!

2023-02-27 15:37 UTC, merged